# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created: Tue Nov 20 00:22:08 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RTQSpiderDlg(object):
    def setupUi(self, RTQSpiderDlg):
        RTQSpiderDlg.setObjectName(_fromUtf8("RTQSpiderDlg"))
        RTQSpiderDlg.resize(487, 231)
        self.gridLayout_3 = QtGui.QGridLayout(RTQSpiderDlg)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonBox = QtGui.QDialogButtonBox(RTQSpiderDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 3, 0, 1, 3)
        self.label = QtGui.QLabel(RTQSpiderDlg)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(RTQSpiderDlg)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(RTQSpiderDlg)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.page)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.yPointCombo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPointCombo.sizePolicy().hasHeightForWidth())
        self.yPointCombo.setSizePolicy(sizePolicy)
        self.yPointCombo.setObjectName(_fromUtf8("yPointCombo"))
        self.gridLayout_4.addWidget(self.yPointCombo, 1, 1, 1, 1)
        self.xPointCombo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPointCombo.sizePolicy().hasHeightForWidth())
        self.xPointCombo.setSizePolicy(sizePolicy)
        self.xPointCombo.setObjectName(_fromUtf8("xPointCombo"))
        self.gridLayout_4.addWidget(self.xPointCombo, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.x1LineCombo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1LineCombo.sizePolicy().hasHeightForWidth())
        self.x1LineCombo.setSizePolicy(sizePolicy)
        self.x1LineCombo.setObjectName(_fromUtf8("x1LineCombo"))
        self.gridLayout_2.addWidget(self.x1LineCombo, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.y1LineCombo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1LineCombo.sizePolicy().hasHeightForWidth())
        self.y1LineCombo.setSizePolicy(sizePolicy)
        self.y1LineCombo.setObjectName(_fromUtf8("y1LineCombo"))
        self.gridLayout_2.addWidget(self.y1LineCombo, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.x2LineCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x2LineCombo.sizePolicy().hasHeightForWidth())
        self.x2LineCombo.setSizePolicy(sizePolicy)
        self.x2LineCombo.setObjectName(_fromUtf8("x2LineCombo"))
        self.gridLayout.addWidget(self.x2LineCombo, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.y2LineCombo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y2LineCombo.sizePolicy().hasHeightForWidth())
        self.y2LineCombo.setSizePolicy(sizePolicy)
        self.y2LineCombo.setObjectName(_fromUtf8("y2LineCombo"))
        self.gridLayout.addWidget(self.y2LineCombo, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 2, 0, 1, 3)
        self.selectCrsBtn = QtGui.QToolButton(RTQSpiderDlg)
        self.selectCrsBtn.setObjectName(_fromUtf8("selectCrsBtn"))
        self.gridLayout_3.addWidget(self.selectCrsBtn, 1, 2, 1, 1)
        self.crsEdit = QtGui.QLineEdit(RTQSpiderDlg)
        self.crsEdit.setObjectName(_fromUtf8("crsEdit"))
        self.gridLayout_3.addWidget(self.crsEdit, 1, 1, 1, 1)
        self.geomTypeCombo = QtGui.QComboBox(RTQSpiderDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomTypeCombo.sizePolicy().hasHeightForWidth())
        self.geomTypeCombo.setSizePolicy(sizePolicy)
        self.geomTypeCombo.setObjectName(_fromUtf8("geomTypeCombo"))
        self.gridLayout_3.addWidget(self.geomTypeCombo, 0, 1, 1, 2)

        self.retranslateUi(RTQSpiderDlg)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RTQSpiderDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RTQSpiderDlg.reject)
        QtCore.QObject.connect(self.geomTypeCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.xPointCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.x1LineCombo.setCurrentIndex)
        QtCore.QObject.connect(self.yPointCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.y1LineCombo.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(RTQSpiderDlg)
        RTQSpiderDlg.setTabOrder(self.geomTypeCombo, self.crsEdit)
        RTQSpiderDlg.setTabOrder(self.crsEdit, self.selectCrsBtn)
        RTQSpiderDlg.setTabOrder(self.selectCrsBtn, self.xPointCombo)
        RTQSpiderDlg.setTabOrder(self.xPointCombo, self.yPointCombo)
        RTQSpiderDlg.setTabOrder(self.yPointCombo, self.x1LineCombo)
        RTQSpiderDlg.setTabOrder(self.x1LineCombo, self.y1LineCombo)
        RTQSpiderDlg.setTabOrder(self.y1LineCombo, self.x2LineCombo)
        RTQSpiderDlg.setTabOrder(self.x2LineCombo, self.y2LineCombo)
        RTQSpiderDlg.setTabOrder(self.y2LineCombo, self.buttonBox)

    def retranslateUi(self, RTQSpiderDlg):
        RTQSpiderDlg.setWindowTitle(QtGui.QApplication.translate("RTQSpiderDlg", "Table to vector converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RTQSpiderDlg", "Output geometry type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RTQSpiderDlg", "Source CRS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RTQSpiderDlg", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RTQSpiderDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RTQSpiderDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RTQSpiderDlg", "Start point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RTQSpiderDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RTQSpiderDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("RTQSpiderDlg", "End point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RTQSpiderDlg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RTQSpiderDlg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.selectCrsBtn.setText(QtGui.QApplication.translate("RTQSpiderDlg", "...", None, QtGui.QApplication.UnicodeUTF8))

